package com.loyalty.engine.clientID2

global org.slf4j.Logger logger

import com.loyalty.engine.model.ShoppingCart
import com.loyalty.engine.model.CartItem

rule "Shopping cart from Mike is passed"
    when
        // check shopping cart
        $sc: ShoppingCart( customerId == "mike")
    then
        // print message
        logger.info("Shopping cart is from Mike");
        $sc.setDiscounted(true);
end

