package com.loyalty.engine.clientID1

global org.slf4j.Logger log

import com.loyalty.model.ShoppingCart
import com.loyalty.model.CartItem

rule "Shopping cart from Alex is passed"
    when
        // check shopping cart
        $sc: ShoppingCart( customerId == "alex")
    then
        // print message
        log.info("Shopping cart is from Alex");
        $sc.setDiscounted(true);
end

rule "Shopping cart with product 'smartphone' is discounted"
   when
        $sc: ShoppingCart($cartItems : shoppingItems)
        $ci: CartItem(product == "smartphone") from $cartItems
   then
        log.info("Shopping cart from " + $sc.getCustomerId() + " has smartphone item: " + $ci.getProduct());
        $sc.setDiscounted(true);
end
