package com.loyalty.demo

global org.slf4j.Logger logger

import com.loyalty.engine.ShoppingCart
import com.loyalty.engine.CartItem

rule "Shopping cart from Alex is passed"
    when
        // check shopping cart
        $sc: ShoppingCart( customerId == "alex")
    then
        // print message
        logger.info("Shopping cart is from Alex");
        $sc.setDiscounted(true);
end

rule "Shopping cart with product iPhone is discounted"
   when
        $sc: ShoppingCart()
        $ci: CartItem( product == "iphone")
   then
        logger.info("Shopping cart from " + $sc.getCustomerId() + " has iPhone item: " + $sc.getShoppingItems().get(0).getProduct());
        $sc.setDiscounted(true);
end
